BusinessConfig:
  ServerUrl: http://localhost:6666/ChinChess
  NeedWarn: true
  HotKeys:
    App:
      线上对战:
        重玩: 重玩 (Alt+R+True)
        悔棋: 悔棋 (Control+Z+True)
        棋盘换向: 棋盘换向 (Alt+D+True)
        认输: 认输 (Alt+F+True)
        和棋: 和棋 (Alt+H+True)
        模拟: 模拟 (Alt+M+True)
      本地对战:
        重玩: 重玩 (Alt+R+True)
        悔棋: 悔棋 (Control+Z+True)
        棋盘换向: 棋盘换向 (Alt+D+True)
      本地残局:
        重玩: 重玩 (Alt+R+True)
        悔棋: 悔棋 (Control+Z+True)
        棋盘换向: 棋盘换向 (Alt+D+True)
  EndGames:
    七星聚会:
      Datas: C04,G05,b13,E24,b25,b58,B71,B74,a77,B83,B85,g94,c96,c97
    征西:
      Datas: A04,G05,b12,b14,C25,a36,a46,c56,c58,B70,B73,B84,g93,e96
    野马操田:
      Datas: E02,F03,G04,F14,E24,d46,c47,c48,e52,C61,b62,b64,B73,e74,B84,g93
    带子入朝:
      Datas: C00,A03,G04,b13,b23,E24,b27,c28,b48,b52,B83,g94
    大九连环:
      Datas: G05,b10,b14,b18,C25,A28,B38,b54,b56,a77,B82,B83,a87,g94
    小征东:
      Datas: A04,G05,b13,b14,C25,a38,a48,c57,b66,c68,B73,B84,g93
    火烧连营:
      Datas: G03,c14,E24,a28,b30,b41,c46,a47,A48,b52,e56,B74,B83,B84,B87,g95
    炮打两狼关:
      Datas: C01,G03,a05,c06,b11,b15,b26,A38,b64,B66,B83,C85,g94
    车打沼河:
      Datas: d01,G03,F14,b23,E24,F25,B32,b48,e56,c57,a58,e70,C82,g93,A94,C96
    边线风雷:
      Datas: A00,c03,b13,F14,E24,G25,b28,c37,B38,E42,B77,e78,B83,C85,B91,g94
    岐山走马:
      Datas: A01,G04,F05,d06,F14,b18,E24,B32,E46,B66,B67,e74,f75,B77,f84,g85,c91,C94,e96
    柳营射猎:
      Datas: F03,G05,b13,F14,E24,b35,a37,E42,C73,e74,c77,B83,B84,D88,g95,a96
    系铃解铃:
      Datas: D03,G05,D06,C10,b14,E24,C25,c37,E42,d47,a77,B81,B84,g93
    解铃系铃:
      Datas: D03,G05,E06,C12,b14,b18,E24,C25,c37,d47,a77,B81,B84,g93
    金井轱辘:
      Datas: G03,b11,b14,b15,E24,c26,a27,E28,A35,B36,A44,B66,D72,B76,C85,D86,e92,g94
    寒松卧壑:
      Datas: A03,G05,b11,b14,b23,C25,b26,B34,C41,a58,b64,c68,c78,B80,B83,B85,g94
    云开雾敛:
      Datas: F03,G24,c47,C70,f73,e74,B81,C82,g93,c97
    分庭抗礼:
      Datas: G04,b06,d15,C20,D23,b25,C32,A42,A52,c75,B84,g95,a97
    辅弼功高:
      Datas: C01,F05,E20,F23,G24,b27,b35,c36,a46,B56,B73,B74,e78,B83,C84,g95,B97
    五虎平西:
      Datas: G04,F14,E24,c35,c37,e52,A63,B71,B74,B75,B84,B85,A88,g93
    馈礼求和:
      Datas: G03,E06,b14,b24,c58,c68,a77,a78,C83,B85,g94,A98
    林冲夜奔:
      Datas: b02,b03,G05,C12,F14,b24,F25,b34,B64,a67,c68,B83,B85,g94
    小溪流水:
      Datas: G04,F05,d07,C14,b15,a18,B38,B64,B84,g95
    金戈玉马:
      Datas: G04,b15,E20,d26,b42,a64,e70,A71,B72,C73,B76,g84,e92
    锦上添花:
      Datas: D04,a10,b21,d23,G24,F25,d48,B60,B73,B74,B83,B84,g95
    隔山打虎:
      Datas: G03,C05,b14,A31,B51,b56,a67,c68,a74,B84,D85,B93,g95
    吹箫引凤:
      Datas: G03,d13,c14,E24,B42,c46,b62,b66,a68,D74,B81,C84,a87,A88,d90,g93
    投桃报李:
      Datas: E02,F03,E06,F14,C21,G24,c31,b33,e70,C82,B85,g93
    长版救主:
      Datas: G04,A08,C13,E24,D25,c26,b27,c28,B42,B46,b62,e74,B83,B84,g95,B97
    远交近攻:
      Datas: a11,G14,c23,B30,c33,B64,C80,C84,B88,g93
    雪印梅花:
      Datas: A01,G03,b14,b16,A20,C23,b25,b26,c27,B32,b36,B74,B83,B85,a88,g94,e96,c98
    二将争先:
      Datas: E02,G05,b10,F14,C20,E24,c28,c38,B55,e56,e74,B81,B83,B86,g95
    绣带拖铃:
      Datas: b02,a05,b14,b18,G23,E24,c36,a56,B67,e74,B78,B83,B85,A86,g94,f95
    罗成摘印:
      Datas: G03,a08,b12,F14,d23,E24,B30,b50,e52,e56,c57,C71,B72,B82,C84,D85,g93,B96
    学富五车:
      Datas: C02,G04,F05,E06,b13,F14,E24,a27,d28,c46,b56,a66,B74,B84,e92,g93,A94,D95,B97
    开窗邀月:
      Datas: a06,b14,b15,G23,E24,B36,A46,A51,b52,c58,B64,e70,C83,B85,a88,e92,g94,B98
    匹马独还:
      Datas: F03,G04,b13,F14,b15,d35,D54,B83,B85,g94
    鱼跃龙门:
      Datas: G04,F05,b13,F14,E24,a26,c27,B30,B32,B36,d37,E42,e52,B63,C64,e74,C84,B85,g93
    海底捞月:
      Datas: C01,G03,b05,C16,B58,B62,B67,c70,f84,f93,g94
    折冲樽俎:
      Datas: G04,b15,D17,b24,d25,E28,b32,D73,e74,B76,e78,B83,g85,A92
    枫桥夜泊:
      Datas: b00,G05,E06,b14,a18,E24,B42,c44,b48,B83,C85,g94
    二龙戏珠:
      Datas: G04,F14,E24,c41,c43,A55,B73,B74,B76,B83,C84,B88,g95,A98
    流星赶月:
      Datas: G04,b24,F25,B62,B65,b66,e70,c74,B83,B85,g94,B98
    狐兔争穴:
      Datas: G03,b15,b22,A24,d26,D36,e74,B82,B83,f84,g94,f95
    新小钓鱼:
      Datas: G03,b14,C23,E24,b31,a47,B51,a57,c67,B85,f93,g94
    宿鸟投林:
      Datas: G04,E06,F14,c20,E24,F25,a46,B73,e74,C84,g93,c95
    武松打虎:
      Datas: G03,b07,b14,b46,d61,B62,c68,B72,c78,C81,A83,B84,a88,g93
    多子西狩:
      Datas: E02,A04,G05,b12,b14,C25,a36,a46,c56,c57,b62,B73,B84,g93,e96
    千里独行:
      Datas: G04,F23,b24,E28,B30,D56,b62,B66,c74,B83,B85,g94
    尺蚓降龙:
      Datas: F03,G04,F14,E24,B42,c55,b58,B84,B86,g95,c98
    晴天霹雳:
      Datas: A02,G05,b12,b13,b14,b24,C25,a67,B74,a77,B83,B85,g94,c96,c97
    巧对花枪:
      Datas: a01,G03,b14,D15,D25,b26,B30,c38,b60,B82,C83,g94,A95,C96
    莺歌燕舞:
      Datas: C04,G05,b13,E24,b25,b32,a58,a68,D74,B77,c78,B81,B83,C85,f93,g94,c96
    多象挂印:
      Datas: G03,A06,b14,E20,b26,b36,b46,b54,B55,A71,B72,e74,g75,B84,a97,c98
    倒转干戈:
      Datas: E02,G05,a10,b14,b21,E24,B30,b60,C68,A70,g74,a83,B85,B86,c93,A98
    巧脱樊笼:
      Datas: D03,G05,b14,C18,b27,C52,c60,B73,c77,D81,A82,B84,B86,g93
    灵丹换骨:
      Datas: G03,a08,b12,F14,b16,F23,E24,B32,c37,B38,B72,B75,C84,D85,B86,g93,e96
    双龙二士:
      Datas: G03,F05,b12,F14,d16,E20,B52,c57,B62,c67,C72,e74,g75,C84,a87,A93
    扑朔迷离:
      Datas: G05,b12,b14,b18,C25,A28,b36,E42,B44,a77,B82,B83,a87,g94,c97
    九九艳阳:
      Datas: F03,G05,C11,b13,b14,E20,c22,b23,b24,D32,D68,a72,f73,B75,B76,B83,f84,g95
    一触即发:
      Datas: A02,G03,b14,c15,E20,b24,C33,E42,C44,b46,a77,A83,B84,B92,B93,g95,a96,c97
    潜龙出渊:
      Datas: b08,F14,c18,G23,F25,B32,b43,e70,B82,B84,B85,B87,g93,a94,c96,A97
    奉诏班师:
      Datas: c00,c01,G23,e52,b60,D67,B74,A80,B83,C85,g94,B96
    廉蔺争功:
      Datas: F03,G05,F14,E24,c28,B30,E46,B52,A53,b64,B72,e74,c78,B84,B88,g93
    炮打中营:
      Datas: E02,G05,E06,b14,C25,C33,a36,a46,c56,A60,c66,e70,e74,B77,A78,B80,f84,B85,B88,f93,g94
    玉盒藏珠:
      Datas: G04,b11,A15,b16,b18,B71,c73,e78,B80,B81,B84,B85,g93,e96
    炮击两狼:
      Datas: A05,b13,b14,G23,E24,a35,c37,A38,a47,b64,e70,C83,B85,g94
    水底擒蛟:
      Datas: a05,b12,b14,G23,E24,B32,c56,c66,B71,B72,e74,a76,B82,C83,B85,A86,g94
    峰回路转:
      Datas: A02,G05,b14,C25,b64,C65,b66,a68,B71,B73,a78,B84,g93,c97,c98
    争芳斗艳:
      Name: 争芳斗艳
      Datas: b01,A02,G05,b14,C25,b64,C65,b66,a68,B73,a78,B84,B86,g93,c97,c98
      Steps: 一炮一平四,車6进4,炮一平四,車6平7,車一进九,車7退6,一兵五平四,帥6进1,車一退一,帥6退1,車一平六,兵4进1,車六退七,兵5平4,帥六进一,車7进7,兵八平七,車7平6,車二进六,車6平5,車二平四,帥6平5,兵七平六,帥5进1,車四进三,兵7平6,車四退八,車5退1,車四进一,車5平4,車四平六,車4进1,帥六进一
    单刀直入:
      Name: 单刀直入
      Datas: G03,F14,D15,b23,E24,b26,c48,B70,C80,B90,g93,A94,C96
      Steps: 車一进四,馬6退8,車一平二,相5退7,車二平三,仕5退6,兵三平四,1兵1平2,車三退九,兵2平3,帥六平五,車1平4,車三进九,兵3平4,帥五平四,車4退6,車三平四,帥4进1,帥四进一,兵1平2,兵四进一,兵2平3,車四平七,車4平6,帥四平五,車6平5,帥五平四,車5进5,車七退三,帥4进1,車七平六,帥4平5,車六平八,帥5平4,兵四平五,帥4平5,兵五平六,帥5平4,兵六平七,帥4平5,車八进三,帥5退1,車八平六,兵3平4,兵七平六,帥5进1,車六平五,帥5平4,車五退七,2兵4平5,兵六平七
    三擒孟获:
      Name: 三擒孟获
      Datas: G03,a08,b12,F14,F23,E24,b33,B48,B58,B75,B80,B81,C84,D85,A86,g93,c97
      Steps: 車二进九,相5退7,車二平三,仕5退6,車三退八,仕6进5,車三进八,仕5退6,炮一平四,兵6平7,兵七平六,帥4进1,兵六进一,帥4平5,兵六进一,帥5平6,炮四退八,兵2进1,車三退一,帥6进1,車三退一,帥6退1,車三平七,兵7进1,炮四平九,兵2平3,車七退七,車5平1,車七进五,車1平6,車七平三,車6退3,車三退四,車6平4,帥六平五,車4平5,帥五平六,帥6进1,車三进六,帥6退1,車三退二,帥6进1,車三平一,兵9平8,車一进二,帥6退1,車一进一,帥6进1,車一平五,車5退4,兵六平五
    六犯中原:
      Name: 六犯中原
      Datas: c00,E02,G03,b10,b11,A12,b14,C23,E24,a28,B51,b52,e56,b60,A64,f73,B85,D93,g94,f95,e96
      Steps: 兵五平六,帥4进1,兵八平七,帥4退1,炮一平六,馬4退2,炮六退四,馬2退4,帥五平六,兵6平5,仕四进五,馬4进2,帥六进一,炮5平1,兵九平八,兵2平1,車九退五,馬2退3,帥六退一,馬3退1,炮六退二,馬1进3,仕五进六,馬3进4,帥六进一
    一擒孟获:
      Name: 一擒孟获
      Datas: G04,F14,b15,E20,C22,E24,c25,b31,B42,B46,e74,B76,e78,B82,B84,g95
      Steps: 車四平二,仕5退6,車二进二,帥5平4,車二平四,帥4进1,車四平五,車3退2,車五退二,車3平6,車五进一,帥4进1,兵八平七,車6进1,車五平四,1兵7进1,兵七平六,帥4平5,兵六平五,帥5平4,車四退一,帥4退1,兵五进一,1兵7平6,車四退六,兵5平6,帥四进一,1兵3平4,帥四进一,兵4平5,兵五平四,帥4平5,兵四平三
    白水升龙:
      Name: 白水升龙
      Datas: G05,b22,b23,F25,C26,b27,E28,c74,B75,B77,B83,B85,B91,g94
      Steps: 車五进七,帥6进1,兵二平三,1兵6进1,帥五平四,仕6退5,兵三进一,帥6进1,兵六平五,帥6平5,車五平一,兵4平5,車一退二,仕5进6,兵七平六,帥5退1,兵三平四,帥5平6,車一退六,兵6进1,車一平四,兵5平6,帥四进一
    拨乱反正:
      Datas: F03,G04,F05,E28,B34,b44,d46,C63,B65,f73,c81,B83,B84,g95
      Steps: 馬三进四,帥5进1,車八进七,帥5进1,馬四进二,車4退3,馬二进四,帥5平6,馬四退二,帥6平5,馬二退三,帥5平4,馬三进四,帥4平5,馬四进六,帥5平4,兵五进一,車4平5,馬六退四,帥4平5,馬四退五,兵6进1,仕六退五,兵4平5,車八平四,兵6进1,車四退七,兵5平6,帥四进一,帥5平4
    激战中原:
      Name: 激战中原
      Datas: A01,F03,G05,b13,F14,E24,a34,b35,b44,e52,A71,C72,e74,B76,B84,B87,B90,g95,c98
      Steps: 車一进九,相5退7,車一平三,帥6进1,兵四进一,仕5进6,車三退一,帥6退1,兵六平五,兵5平6,帥四进一,兵7平6,帥四退一,仕6退5,炮五平七,2炮2平3,炮七退四,炮3进7,車三进一,帥6进1,車三退六,炮2进2,帥四平五,仕5进6,帥五进一,炮2平9,帥五平六,仕4进5,兵五进一,炮3平2,兵五进一,炮2退7,車三进五,帥6退1,兵五进一,仕6退5,車三平五,兵8平7,車五平八,炮2平5,車八退二,帥6进1,車八平四,帥6平5,車四退四
    双马联营:
      Name: 双马联营
      Datas: b01,G05,E06,b07,b12,A15,b16,E24,b25,B36,d62,B72,B84,B87,e92,g93,B95,d96
      Steps: 兵二平三,帥6平5,一兵三平四,帥5平6,兵三平四,帥6平5,馬三进四,兵3进1,相七进九,兵3平4,馬七退六,帥5平4,兵八平七,相5退3,兵七进一,帥4进1,一兵四平五,帥4进1,兵四平五,帥4平5,馬六进五,兵8平7,馬五退七,1兵7平6,馬七退五,2兵6平5,相九进七,兵7进1,相七退五,帥5退1,兵七平八,兵7进1,相五进三,兵6平5,馬四退五,兵5进1,帥六进一,兵5平6
    诱羌增灶:
      Name: 诱羌增灶
      Datas: c03,A04,G05,F23,b24,b26,b62,B65,B73,c74,e78,B83,B85,g94
      Steps: 車六平五,帥6平5,車五进四,1兵4平5,車五退五,1兵6平5,帥五进一,兵6进1,相一进三,仕4退5,兵七进一,帥5平4,兵五平六,仕5进4,兵七进一,仕4退5,兵七平六,帥4平5,兵六平五,帥5平6,兵五平四,帥6平5,兵四平五
    螳臂挡猿:
      Name: 螳臂挡猿
      Datas: G04,F14,b18,b24,c46,B65,B76,B82,B83,B84,g95
      Steps: 車三进三,兵5平6,帥四进一,兵6进1,帥四退一,帥5平6,車三进一,帥6进1,帥四平五,兵6平5,兵五进一,帥6平5,車三退七,兵5进1,帥五平四,兵3进1,車三平五,帥5平4,車五平六,帥4平5,車六退一,兵5平4,帥四进一
    圯桥进展:
      Name: 圯桥进展
      Datas: G03,b15,F25,b43,b64,B77,B80,B83,B84,e92,g95,c96
      Steps: 兵六进一,兵4进1,車三进九,帥4进1,兵六进一,帥4进1,車三平六,帥4平5,車六退九,兵8平7,車六平五,兵5进1,帥四进一,兵1平2,兵五进一,兵2平3,兵五进一,兵3平4,兵五进一,帥5平4
